package fenetre;

/**
 *
 * @author Belouh
 */
public class Login extends javax.swing.JFrame {

    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        conteneur = new javax.swing.JPanel();
        titre = new javax.swing.JLabel();
        pseudo = new javax.swing.JTextField();
        ipServeur = new javax.swing.JTextField();
        btnValidation = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Connexion sur le projet Chat");
        setName("frameLogin"); // NOI18N

        conteneur.setName("conteneur"); // NOI18N

        titre.setBackground(new java.awt.Color(255, 255, 255));
        titre.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        titre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titre.setText("Connexion ...");
        titre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        pseudo.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        pseudo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pseudo.setText("Votre Pseudo ...");
        pseudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pseudoActionPerformed(evt);
            }
        });

        ipServeur.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        ipServeur.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ipServeur.setText("Ip du Serveur ...");
        ipServeur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ipServeurActionPerformed(evt);
            }
        });

        btnValidation.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        btnValidation.setText("Valider");
        btnValidation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnValidationMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout conteneurLayout = new javax.swing.GroupLayout(conteneur);
        conteneur.setLayout(conteneurLayout);
        conteneurLayout.setHorizontalGroup(
            conteneurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(conteneurLayout.createSequentialGroup()
                .addGroup(conteneurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(conteneurLayout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(ipServeur, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(conteneurLayout.createSequentialGroup()
                        .addGap(268, 268, 268)
                        .addComponent(titre, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(conteneurLayout.createSequentialGroup()
                        .addGap(435, 435, 435)
                        .addComponent(btnValidation, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(219, Short.MAX_VALUE))
            .addGroup(conteneurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(conteneurLayout.createSequentialGroup()
                    .addGap(224, 224, 224)
                    .addComponent(pseudo, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(217, Short.MAX_VALUE)))
        );
        conteneurLayout.setVerticalGroup(
            conteneurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(conteneurLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(titre, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(173, 173, 173)
                .addComponent(ipServeur, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(btnValidation, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(173, Short.MAX_VALUE))
            .addGroup(conteneurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(conteneurLayout.createSequentialGroup()
                    .addGap(224, 224, 224)
                    .addComponent(pseudo, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(431, Short.MAX_VALUE)))
        );

        ipServeur.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(conteneur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(conteneur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pseudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pseudoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pseudoActionPerformed

    private void ipServeurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ipServeurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ipServeurActionPerformed

    private void btnValidationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnValidationMouseClicked
        System.out.println("Le pseudo que vous avez rentrer est "+pseudo.getText());
        System.out.println("Le ip du Serveur est de "+ipServeur.getText());
    }//GEN-LAST:event_btnValidationMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnValidation;
    private javax.swing.JPanel conteneur;
    private javax.swing.JTextField ipServeur;
    private javax.swing.JTextField pseudo;
    private javax.swing.JLabel titre;
    // End of variables declaration//GEN-END:variables
}
